### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'draw' 

### ISSUE THREAD

**Issue by mj-watts** [jsoma/mapsheet#2]
Getting Uncaught TypeError: Object #<Object> has no method 'draw' 
Getting on all the example files too.

Something has changed with the new tabletop.js as the old version included here is working fine.

**Comment by jsoma** [comment]
Just dropped in the very newest Tabletop, seems to be working fine now - although I don't doubt that there must have been a bug hiding in either Tabletop or Mapsheet
