### ISSUE TITLE
Do custom marker icons work?

### ISSUE THREAD

**Issue by Kirkman** [jsoma/mapsheet#5]
I have a spreadsheet with an "icon url" column, populated with PNG urls. However Mapsheet is not displaying these icons.

Here's the spreadsheet:
https://docs.google.com/spreadsheet/ccc?key=0Ah9eiJcTTiAKdDV4cENxcWgyRE9lUzdYWFRxTFJXNmc#gid=0

Here's the map:
http://www.stltoday.com/news/multimedia/where-were-you-during-the-flood-of/html_247ad579-1974-519d-85c3-67c33f2fef4f.html

In the console, if I inspect a given myMap.points.marker, I can see it has `icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'`

So why isn't the green dot marker displayed on the map?

**Comment by jsoma** [comment]
I don't know if they just plain never worked or Google updated something on their end, but I just put in a fix with 0cf5c07a8c222c4f9af94d93f9c0496a4998d9a4 that should have them cleaned up.
